# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(default=b'e24d76f7-30de-4478-895e-5942242f07ee', editable=False, primary_key=True, serialize=False),
        ),
    ]
