# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160719_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(default=b'4c30b82b-3b21-449d-bed4-d62cfef02c39', editable=False, primary_key=True, serialize=False),
        ),
    ]
