# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160719_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='timestamp_registration',
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(default=b'5a9caf58-a46d-43f1-90a1-ae484535f9d7', editable=False, primary_key=True, serialize=False),
        ),
    ]
