# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160719_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(default=b'910073ec-08f4-453a-98b5-89be753dbca0', editable=False, primary_key=True, serialize=False),
        ),
    ]
