# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160719_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.UUIDField(default=b'ef18883f-3c63-48fe-a8df-d2d07186a5a2', editable=False, primary_key=True, serialize=False),
        ),
    ]
